# Generated by Django 2.2.7 on 2019-11-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_recipe"),
    ]

    operations = [
        migrations.RenameField(model_name="recipe", old_name="tag", new_name="tags",),
    ]
